//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class donetask
{
    public int id { get; set; }
    public int task_id { get; set; }
    public int worktime { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public int user_id { get; set; }

    public virtual task task { get; set; }
    public virtual user user { get; set; }
}

public partial class project
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public project()
    {
        this.tasks = new HashSet<task>();
        this.users = new HashSet<user>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public string customer { get; set; }
    public string description { get; set; }
    public string github_username { get; set; }
    public string github_reponame { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<task> tasks { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<user> users { get; set; }
}

public partial class task
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public task()
    {
        this.donetasks = new HashSet<donetask>();
        this.task1 = new HashSet<task>();
    }

    public int id { get; set; }
    public Nullable<int> task_id { get; set; }
    public Nullable<int> project_id { get; set; }
    public string name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<donetask> donetasks { get; set; }
    public virtual project project { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<task> task1 { get; set; }
    public virtual task task2 { get; set; }
}

public partial class user
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {
        this.projects = new HashSet<project>();
        this.donetasks = new HashSet<donetask>();
    }

    public int id { get; set; }
    public string username { get; set; }
    public string password { get; set; }
    public string salt { get; set; }
    public string firstname { get; set; }
    public string lastname { get; set; }
    public Nullable<System.DateTime> created { get; set; }
    public Nullable<System.DateTime> modified { get; set; }
    public string role { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<project> projects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<donetask> donetasks { get; set; }
}
